fix: Print verbose errors in cudf deps updater (#16332)
Summary:
## Description

This PR updates the `update-cudf-deps.sh` to not silently exit without any message or effect when, for example, `read` fails due to GH rate limiting and throws a verbose message such as

```bash
Error: Failed to fetch VERSION file from branch main
  Try: `gh auth login` (or set GH_TOKEN) before running this script
  Create a GitHub personal access token at https://github.com/settings/tokens/new
  (Select scope: public_repo)
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/16332

Reviewed By: tanjialiang

Differential Revision: D100439867

Pulled By: xiaoxmeng

fbshipit-source-id: 467a7b6c637a70c7f5a4bd3343e06efd10d518fb